### PR TITLE
Query issue

### PR DESCRIPTION
**Pull request by stephenmoloney**
Hi,

here a a few minor changes to the pull request. 

1. adds the "?" only if the query is not :nil.
2. use the image from my profile rather than one external to the repo.

Thanks for this BTW, 
:+1:

### CODE REVIEW

**Comment by kagux** [comment]
@stephenmoloney, good catch about "?"!
there seems to be merge conflict though, could you resolve it?

**Comment by stephenmoloney** [comment]
sorry, can't figure out how to resolve it right now.  Do you mind?

**Comment by stephenmoloney** [comment]
actually hold off on this for a bit. 

I am currently checking if I can change the library to `:hackney` in which case, this pull request might not be required. 

I'll post back here later.

**Comment by kagux** [comment]
Alright. Btw something I noticed as well, some images are behind redirect and it'd be nice to follow it. Like this one https://imgredirect.milanuncios.com/fg/1932/90/motos-de-carretera/Yamaha-MT07-193290824_4.jpg

**Comment by stephenmoloney** [comment]
true. I'll add that to the issues list as a new feature for 0.0.3. I'm about to release 0.0.2. Thanks for all your input. 

:smile:

**Pull request closed without merging**
